### ISSUE TITLE
Separated color

### ISSUE THREAD

**Issue by tistoubapt** [JamsheedMistri/chrometheme.studio#2]
Hello

Thank you very much for customizing the themes
I use it for Edge Chromium and I would like to know if it is possible to separate the colors of the Tab text (Universal) and the Tab Txt in the display at the bottom of the page (when loading a page)

**Comment by JamsheedMistri** [comment]
Hello, I don't understand what "tab text in the display at the bottom of the page" is, can you send a screenshot or give an example?

**Comment by tistoubapt** [comment]
Hello

I was talking about these 2 txt (image taken from the web)

https://ibb.co/ypGZbKQ

But it's okay, I managed to have 1 color for the tab and 1 color for the display at the bottom of the page, but I don't really know how

Thanks

**Comment by JamsheedMistri** [comment]
I don't think this is controllable separately via manifest v2, but if you have any ideas feel free to make a PR or provide teechnical details here. Closing for now!

**Comment by tistoubapt** [comment]
I don't know at all how I did it, but I did it from your website by modifying the colors
In black on the active tab (text), and in white at the bottom of the page (text) : 

https://ibb.co/9pCwX7d

Thanks for your website

PS: A small suggestion, it would be good to have a total overview of the page (we could see the part at the bottom of the page in particular)
